name: 01 - Information Gathering

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display server information from secrets
        run: |
          echo "🚀 Pipeline Started"
          echo "Target IP: ${{ secrets.AWS_SERVER_IP }}"
          echo "Target Domain: ${{ secrets.AWS_SERVER_DOMAIN }}"

      - name: Test connection to server
        run: |
          ping -c 2 ${{ secrets.AWS_SERVER_IP }}
